on:
  workflow_dispatch:
    inputs:
      repoOrg:
        description: "Repo Org"
        required: true
        default: "pomber"
      repoName:
        description: "Repo Name"
        required: true
        default: "didact"
      starCount:
        description: "Star Count"
        required: true
        default: "100"
      showLogin:
        description: "Show stargazers' login names as well as their names"
        required: true
        type: boolean
        default: false
      showRepo:
        description: "Show the repo name in each stargazer card"
        required: true
        type: boolean
        default: true
      duration:
        description: "Duration (seconds)"
        required: false
        default: "15"
      fps:
        description: "Framerate (FPS)"
        required: false
        default: "30"
      width:
        description: "Width (px)"
        required: false
        default: "960"
      height:
        description: "Height (px)"
        required: false
        default: "540"
      scale:
        description: "Scale (recommended: width/512)"
        required: false
        default: "1.875"
name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies (ffmpeg and fonts)
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yq --no-install-recommends \
            ffmpeg \
            fonts-noto-core fonts-noto-cjk fonts-noto-color-emoji fonts-noto-mono
      - name: Install dependencies (node modules)
        run: npm i
      - name: Inject configurations
        # Inject to file, inspect to logs
        run: echo $WORKFLOW_INPUT | tee input-props.json | jq -C '.'
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - name: Render video
        # speed up: GHA hosted runners have two cores
        run: npm run build -- --props="./input-props.json" --concurrency=2
        env:
          REMOTION_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload video
        uses: actions/upload-artifact@v3
        with:
          name: out.mp4
          path: out.mp4
